using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

namespace Rgd.GraphQL.Server.Model;

/// <summary>Reads and validates the model file. Any problem is reported at once, and fails the startup.</summary>
public static partial class ModelLoader
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true,
        // A typo in the model must not silently drop a setting.
        UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
    };

    private static readonly HashSet<string> ReservedFieldNames = ["and", "or", "not"];

    public static DataModel Load(string path)
    {
        if (!File.Exists(path))
        {
            throw new ModelException($"The model file '{path}' does not exist.");
        }

        using var stream = File.OpenRead(path);
        return Load(stream, path);
    }

    public static DataModel Load(Stream stream, string source = "model")
    {
        DataModel? model;
        try
        {
            model = JsonSerializer.Deserialize<DataModel>(stream, JsonOptions);
        }
        catch (JsonException e)
        {
            throw new ModelException($"The model '{source}' is not valid JSON: {e.Message}", e);
        }

        if (model is null)
        {
            throw new ModelException($"The model '{source}' is empty.");
        }

        var errors = Validate(model);
        if (errors.Count > 0)
        {
            throw new ModelException(
                $"The model '{source}' is invalid:{Environment.NewLine}  - {string.Join(Environment.NewLine + "  - ", errors)}");
        }

        return model;
    }

    public static IReadOnlyList<string> Validate(DataModel model)
    {
        ArgumentNullException.ThrowIfNull(model);

        var errors = new List<string>();
        if (model.Entities.Count == 0)
        {
            errors.Add("at least one entity must be declared.");
        }

        var typeNames = new HashSet<string>(StringComparer.Ordinal);
        var rootFields = new HashSet<string>(StringComparer.Ordinal);
        foreach (var entity in model.Entities)
        {
            var where = $"entity '{entity.Name}'";
            if (!GraphQLName().IsMatch(entity.Name ?? string.Empty))
            {
                errors.Add($"{where}: the name is not a valid GraphQL type name.");
                continue;
            }

            if (!typeNames.Add(entity.Name!))
            {
                errors.Add($"{where}: declared twice.");
            }

            if (!SqlIdentifier().IsMatch(entity.Table ?? string.Empty))
            {
                errors.Add($"{where}: the table '{entity.Table}' is not a valid SQL identifier.");
            }

            if (entity.Schema is not null && !SqlIdentifier().IsMatch(entity.Schema))
            {
                errors.Add($"{where}: the schema '{entity.Schema}' is not a valid SQL identifier.");
            }

            if (entity.PluralName is not null && !GraphQLName().IsMatch(entity.PluralName))
            {
                errors.Add($"{where}: the plural name '{entity.PluralName}' is not a valid GraphQL name.");
            }

            if (entity.DefaultPageSize < 1 || entity.MaxPageSize < entity.DefaultPageSize)
            {
                errors.Add($"{where}: page sizes must satisfy 1 <= defaultPageSize <= maxPageSize.");
            }

            var queries = entity.KeyFields.Any()
                ? new[] { entity.SingleQueryName, entity.ListQueryName, entity.CountQueryName }
                : [entity.ListQueryName, entity.CountQueryName];
            foreach (var query in queries.Where(q => !rootFields.Add(q)))
            {
                errors.Add($"{where}: the query field '{query}' is already generated by another entity.");
            }

            ValidateFields(entity, where, errors);
        }

        return errors;
    }

    private static void ValidateFields(EntityModel entity, string where, List<string> errors)
    {
        if (entity.Fields.Count == 0)
        {
            errors.Add($"{where}: at least one field must be declared.");
        }

        var fieldNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var field in entity.Fields)
        {
            var fieldWhere = $"{where}, field '{field.Name}'";
            if (!GraphQLName().IsMatch(field.Name ?? string.Empty) || field.Name!.StartsWith("__", StringComparison.Ordinal))
            {
                errors.Add($"{fieldWhere}: the name is not a valid GraphQL field name.");
                continue;
            }

            if (ReservedFieldNames.Contains(field.Name))
            {
                errors.Add($"{fieldWhere}: the name is reserved by the filter combinators (and, or, not).");
            }

            if (!fieldNames.Add(field.Name))
            {
                errors.Add($"{fieldWhere}: declared twice.");
            }

            if (!SqlIdentifier().IsMatch(field.Column ?? string.Empty))
            {
                errors.Add($"{fieldWhere}: the column '{field.Column}' is not a valid SQL identifier.");
            }

            if (!Enum.IsDefined(field.Type))
            {
                errors.Add($"{fieldWhere}: unknown type.");
            }

            if (field.Transform is { } transform)
            {
                if (field.Type is not (FieldType.String or FieldType.Id))
                {
                    errors.Add($"{fieldWhere}: only String and ID fields can be tokenized.");
                }

                if (string.IsNullOrWhiteSpace(transform.ClassName)
                    || string.IsNullOrWhiteSpace(transform.PropertyName)
                    || string.IsNullOrWhiteSpace(transform.Jurisdiction))
                {
                    errors.Add($"{fieldWhere}: className, propertyName and jurisdiction of the transform are required.");
                }
            }
        }
    }

    [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_]*$")]
    private static partial Regex GraphQLName();

    /// <summary>Identifiers are embedded in the generated SQL, hence the strict character set.</summary>
    [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_$#@]*$")]
    private static partial Regex SqlIdentifier();
}

public sealed class ModelException : Exception
{
    public ModelException()
    {
    }

    public ModelException(string message)
        : base(message)
    {
    }

    public ModelException(string message, Exception innerException)
        : base(message, innerException)
    {
    }
}
