Krb5LoginContext {
    com.sun.security.auth.module.Krb5LoginModule required
    refreshKrb5Config=true
    useTicketCache=false
    forwardable=true
    renewable=false
    storeKey=true
    doNotPrompt=true
    useKeyTab=true
    isInitiator=false
    debug=false
    keyTab="file://config/certs/rgd.keytab"
    principal="HTTP/tokenization-secure-gvz-e01.corp.ubp.ch";
};

Krb5LoginContextInit {
    com.sun.security.auth.module.Krb5LoginModule required
    refreshKrb5Config=true
    useTicketCache=false
    forwardable=true
    renewable=false
    debug=false
    storeKey=true
    useKeyTab=true
    doNotPrompt=true
    isInitiator=true
    keyTab="file://config/certs/rgd.keytab"
    principal="HTTP/tokenization-secure-gvz-e01.corp.ubp.ch";
};
