using System.Text;
using Rgd.GraphQL.Server.Model;

namespace Rgd.GraphQL.Server.Tests.Model;

public class ModelLoaderTests
{
    [Fact]
    public void Loads_the_shipped_model()
    {
        var model = ModelLoader.Load(Path.Combine(AppContext.BaseDirectory, "config", "model.json"));

        var person = Assert.Single(model.Entities);
        Assert.Equal("PERSON", person.Table);
        Assert.Equal("person", person.SingleQueryName);
        Assert.Equal("persons", person.ListQueryName);
        Assert.Equal("personsCount", person.CountQueryName);
        Assert.Equal("id", Assert.Single(person.KeyFields).Name);
        Assert.Equal("shortString", person.GetField("firstName").Transform!.PropertyName);
        Assert.Null(person.GetField("city").Transform);
    }

    [Theory]
    [InlineData("Person", "persons")]
    [InlineData("Company", "companies")]
    [InlineData("Day", "days")]
    [InlineData("Address", "addresses")]
    [InlineData("Branch", "branches")]
    public void Pluralizes_the_list_query_name(string name, string expected)
    {
        var entity = new EntityModel { Name = name, Table = "T" };

        Assert.Equal(expected, entity.ListQueryName);
    }

    [Fact]
    public void Honours_an_explicit_plural_name()
    {
        var entity = new EntityModel { Name = "Person", PluralName = "People", Table = "T" };

        Assert.Equal("people", entity.ListQueryName);
    }

    [Fact]
    public void Rejects_a_missing_file()
    {
        var e = Assert.Throws<ModelException>(() => ModelLoader.Load("/does/not/exist.json"));

        Assert.Contains("does not exist", e.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Rejects_malformed_json()
    {
        var e = Assert.Throws<ModelException>(() => Load("{ \"entities\": [ "));

        Assert.Contains("not valid JSON", e.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Rejects_an_unknown_property_rather_than_ignoring_it()
    {
        var e = Assert.Throws<ModelException>(() => Load("""
            { "entities": [ { "name": "A", "table": "A", "colums": [] } ] }
            """));

        Assert.Contains("colums", e.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Rejects_an_unknown_field_type()
    {
        Assert.Throws<ModelException>(() => Load("""
            { "entities": [ { "name": "A", "table": "A", "fields": [ { "name": "a", "column": "A", "type": "Blob" } ] } ] }
            """));
    }

    [Fact]
    public void Reports_every_error_at_once()
    {
        var e = Assert.Throws<ModelException>(() => Load("""
            {
              "entities": [
                {
                  "name": "Person", "table": "PERSON; DROP TABLE X",
                  "fields": [
                    { "name": "id", "column": "ID", "type": "Int", "key": true },
                    { "name": "id", "column": "ID2", "type": "Int" },
                    { "name": "and", "column": "AND_", "type": "String" },
                    { "name": "age", "column": "AGE", "type": "Int",
                      "transform": { "className": "Person", "propertyName": "age", "jurisdiction": "CH" } }
                  ]
                },
                { "name": "Person", "table": "OTHER", "fields": [ { "name": "x", "column": "X", "type": "String" } ] }
              ]
            }
            """));

        Assert.Contains("'PERSON; DROP TABLE X' is not a valid SQL identifier", e.Message, StringComparison.Ordinal);
        Assert.Contains("field 'id': declared twice", e.Message, StringComparison.Ordinal);
        Assert.Contains("reserved", e.Message, StringComparison.Ordinal);
        Assert.Contains("only String and ID fields can be tokenized", e.Message, StringComparison.Ordinal);
        Assert.Contains("entity 'Person': declared twice", e.Message, StringComparison.Ordinal);
        Assert.Contains("already generated by another entity", e.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Rejects_an_empty_model()
    {
        var e = Assert.Throws<ModelException>(() => Load("{ \"entities\": [] }"));

        Assert.Contains("at least one entity", e.Message, StringComparison.Ordinal);
    }

    private static DataModel Load(string json) =>
        ModelLoader.Load(new MemoryStream(Encoding.UTF8.GetBytes(json)));
}
